### ISSUE TITLE
Change the repo name to Gatsby naming format.

### ISSUE THREAD

**Issue by cwray-tech** [rudderlabs/gatsby-plugin-rudderstack#1]
Hey, @thtmnisamnstr  

I recommend that we update the repo name to be **gatsby-plugin-rudderstack** due to [the naming conventions that Gatsby requires](https://www.gatsbyjs.com/docs/naming-a-plugin/) in order to be listed in their plugin marketplace.

Is that okay with you? 

This will make it easier for people to find the plugin on Github if the repo has the same name as the plugin itself.

**Comment by cwray-tech** [comment]
The reason I recommend changing the repo name is that it would be good to have the same repo name as the plugin for easily finding the plugin on Github.

**Comment by thtmnisamnstr** [comment]
@cwray-tech I updated the repo name.
