### ISSUE TITLE
[ENHANCEMENT] Add Lamda Function for Ad Blockers & Page Speed

### ISSUE THREAD

**Issue by cwray-tech** [rudderlabs/gatsby-plugin-rudderstack#5]
**Is your feature request related to a problem? Please describe.**
I am adding this feature request as an issue, so that we can track progress on this, and add a pull to relate this to.

**Describe the solution you'd like**
Based on the [original project requirements](https://github.com/rudderlabs/rudder-server/issues/655), we need the ability to proxy events through a Lambda Function, if a site developer so chooses. 

This is to outsource browser work, and send data that needs to be sent to Rudderstack to a Lambda function, so that the function can take care of sending the data to Rudderstack.

Using this approach, developers can make event tracking more asynchronous and therefore speed up site speed.

**Comment by cwray-tech** [comment]
Gavin and Kostas,
 
I would like to start a conversation about the Lambda Function feature here on Github to hear more of your thoughts about this, and to share my concerns and thinking.

I am still not completely convinced that doing this feature right now is the best for the Gatsby plugin integration. 

Below I will share my thoughts as to what are my concerns, and how I think we ought to go forward with it. 

I am not set in stone on this, and of course will do what you believe to be the best route.

## Concerns
- Adding a feature that is not requested (yet) gives the plugin more dependencies and complexities that may be hard to maintain in the future.
- Maybe we should see how the current plugin integration works with more Gatsby sites before we try to make a function that only a percentage of our users might use.
- If I was going to maintain this project going forward, I would rather only maintain a plugin that utilizes Rudderstack's base features, rather than something that may add extra functionality that is not referenced in the Rudderstack documentation.
- The current plugin has not been adequately tested yet, and I want to ensure that it works well before adding more complexity to it.

## Ideas
- Continue testing the Gatsby plugin as is, and see if we get undesirable data from the updated Rudderstack blog that is using this.
- If we are getting undesirable data and a much slower site speed from too much browser work, maybe we should revisit the base functionality of the browser code and try optimizing it first.
- If the base Rudderstack code does not need any optimizations, and it is refactored as we would like, then maybe we should extend a lambda function to all Rudderstack users.
  - This would ensure that all users are experiencing satisfactory speed of Rudderstack, whether utilizing Gatsby, or not.
  - This would also be great for sites where companies are not getting satisfactory data due to ad blockers. (We would have a Lambda Function to offer them and integrate.)

As I before mentioned, I am not opposed completely to going forward, and I will do this integration as I have time if you do decide to go ahead. 

Being not experienced in Lambda, I will require a couple solid weeks of study before I can commit to having this finished in the best way for you guys. I don't want to release junk, and I do feel if I tried to hack something together in the way that I had initially planned, it will not be satisfactory in any way.

Thanks so much, and looking forward to hearing your thoughts and input on this as well as any other team members involved.

Thank you!
Chris

@thtmnisamnstr

**Comment by thtmnisamnstr** [comment]
I'd still like it. Nobody has requested it yet, but it is an issue that sites with event instrumentation are known to run into. It should be configurable on the Gatsby plugin, so you could choose to not configure it and use the Gatsby plugin as it works currently, or you could choose to configure for the Netlify function and only then route through Netlify.

I completely get your concerns, but I think it still makes sense to move forward with it.

- Gavin

**Comment by cwray-tech** [comment]
@thtmnisamnstr great! I will need a couple more weeks to finish this then. Thanks so much for all your patience with me so far on this project. I've greatly appreciated it.

**Comment by cwray-tech** [comment]
@mister-josuecedeno here is the issue for the plugin side that is for implementing the Lambda function with the Gatsby plugin.

**Comment by l-hendriks** [comment]
I'm not sure what problem this solves? Using API Gateway proxies (and my PR #9) you can hide rudderstack completely behind proxies and it works even with ad blockers turned on. No lambda function needed (tested with ublock origin).
